---
- name: Setting hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when: ansible_facts['nodename'] != inventory_hostname

- name: Install basic packages
  apt:
    name: "{{ base_packages }}"
    update_cache: yes
    state: present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Installing basic python packages
  ansible.builtin.pip:
    name: "{{ base_python_pkgs }}"
    executable: pip3
