---
#
## Ansible user data
#

# Uncomment this lines if you want to define you user or/and password in vault/sudo.yaml (this file is encrypted and ignored by git)
# ansible_user: "{{ vault_ansible_user }}"
# ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"

#
## Users role evalues
#
users:
  - username: "matias.uhart"
    groups:

  - username: "serafin.cepeda"
    groups:

  - username: "navid.khan"
    groups:

remove_users: {}

#
## Base Config and Pakages role values
#

# Base packages SO
base_packages:
  - net-tools
  - vim
  - dnsutils
  - htop
  - python3
  - python3-pip
  - ca-certificates
  - curl
  - apt-transport-https
  - lsb-release
  - gnupg

# Base python packages
base_python_pkgs:
  - Setuptools
